### PR TITLE
Add tasks and workers point in time charts

### PR DESCRIPTION
**Pull request by helfi92**
Requires a rebase on `main` once https://github.com/taskcluster/taskcluster-provisioning-simulator/pull/16 has been merged.
Refers to https://github.com/taskcluster/taskcluster/issues/3322.

### CODE REVIEW

**Comment by helfi92** [comment]
Screen Shot 2020-08-10 at 4 34 07 PM

Note to self:
* We can use the `msToHuman` function to make the x axis more readable. I'm waiting on the issue8 branch to merge before refactoring anything since it's currently not exposed to other files. Once this is done, we should add units to the chart axes.

**Comment by helfi92** [comment]
Rebasing on main after #8 still throws an error when using the new analyze method:

```
commit bff2b8affc1d573b3f5803185d486f1a686fe896
Author: Hassan Ali <helfi92@gmail.com>
Date:   Tue Aug 11 08:29:41 2020 -0400

    WIP - not working

diff --git a/src/datastore.js b/src/datastore.js
index 7430f24..3fd12ab 100644
--- a/src/datastore.js
+++ b/src/datastore.js
@@ -185,6 +185,7 @@ class DataStore {
     const result = [];
     const generateMetrics = time => {
       const sample = {time};
+      console.log('metrics: ', metrics)
       for (let [m, fn] of Object.entries(metrics)) {
         sample[m] = fn(state);
       }
diff --git a/src/ui/views/PointInTimeMetrics.jsx b/src/ui/views/PointInTimeMetrics.jsx
index 808b182..ad3a58c 100644
--- a/src/ui/views/PointInTimeMetrics.jsx
+++ b/src/ui/views/PointInTimeMetrics.jsx
@@ -2,8 +2,21 @@ import React from 'react';
 import { hot } from 'react-hot-loader';
 import LinearGraph from '../Components/LinearGraph';
 import analysis from '../analysis';
+import DataStore from '../../datastore';
 
 const PointInTimeMetrics = () => {
+    const result = analysis.analyze({
+        interval: 1000,
+        metrics: {
+            pendingTasks: DataStore.pendingTasks,
+            // runningTasks: DataStore.runningTasks,
+            // resolvedTasks: DataStore.resolvedTasks,
+            // requestedWorkers: DataStore.requestedWorkers,
+            // runningWorkers: DataStore.runningWorkers,
+            // shutdownWorkers: DataStore.shutdownWorkers,
+        },
+    });
+    console.log('r: ', result);
     const events = analysis.datastore.events;
     const timeAnalysis = new Map();
     const state = {
```

Error:

```
 Uncaught TypeError: fn is not a function
    generateMetrics datastore.js:190
    analyze datastore.js:206
    analyze analysis.jsx:30
    React 3
    wrappedHook react-hot-loader.development.js:2758
    analyze analysis.jsx:30
    PointInTimeMetrics PointInTimeMetrics.jsx:8
    ProxyFacade react-hot-loader.development.js:827
    React 11
    unstable_runWithPriority scheduler.development.js:653
    React 6
```

**Comment by djmitche** [comment]
I think you want
```
+import {DataStore} from '../../datastore';
```

**Comment by petemoore** [comment]
> I think you want
> 
> ```
> +import {DataStore} from '../../datastore';
> ```

~Should that be `import { DataStore } from '../../datastore';` after #taskcluster/taskcluster#3374 ?~

Sorry, just realised this isn't the taskcluster monorepo! :-)

**Comment by djmitche** [comment]
Haha, but you're right, and also I'm sure Hassan will type it that way :+1:

**Review by djmitche — APPROVED** [review]
Looks great!

**Pull request merged**
